[phases.setup]
nixPkgs = ["nodejs_18", "ffmpeg", "python3", "python3Packages.pip"]

[phases.install]
cmds = [
  "python3 -m pip install --user -U yt-dlp",
  "npm install --legacy-peer-deps"
]

[start]
cmd = "npm start"
