[phases.setup]
nixPkgs = ["nodejs_18", "ffmpeg", "curl"]

[phases.install]
cmds = [
  "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp",
  "chmod a+rx /usr/local/bin/yt-dlp",
  "npm install --legacy-peer-deps"
]

[start]
cmd = "npm start"
